# @note This compose file is for testing & development purposes
version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      catalyst:
    depends_on:
     - db

  db:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      catalyst:

networks:
  catalyst:
    driver: bridge

volumes:
    mysql_data:
